name: AWS CDK Deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - deploy-main-alpha
permissions:
  contents: read
env:
  AWS_REGION: eu-north-1 
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          cd infrastructure
          yarn install --frozen-lockfile
          cd ..

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create AWS Profile
        run: |
          mkdir -p ~/.aws
          echo "[dev-wayless]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=${{ env.AWS_REGION }}" >> ~/.aws/credentials

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Run deployment
        run: ./deploy.sh